# Generated by Django 5.2.17 on 2026-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpillDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('area_km2', models.FloatField()),
                ('confidence', models.FloatField()),
                ('classification', models.CharField(choices=[('OIL_SPILL', 'Oil spill'), ('LOOK_ALIKE', 'Look-alike'), ('UNVERIFIED', 'Unverified')], max_length=20)),
                ('detected_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('vessel_type', models.CharField(max_length=40)),
                ('flag', models.CharField(max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_knots', models.FloatField(default=0)),
                ('course', models.FloatField(default=0)),
                ('status', models.CharField(default='Underway', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
